theme: minima
title: My First Blog
author: Jeremiah Bogard
email: bogard.jeremiah@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  This is my first blog post. I created this site with the help of @github-learning-lab bot.
  The different languages I used are Markdown and jekyll.
  I used the techniques I learned yesterday. Those techniques are how to make changes
  and code in github.

# social links
twitter_username: I do not have a twitter account # DO NOT include the @ character, or else the build will fail!
github_username:  JeremiahB-webDev # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
